### ISSUE TITLE
Phantom 'Farm' to 'Group' Delivery Option Change

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#26]
Looked at 'Patchwork Gardens' customer...changed name to 'Patchwork Garde'. Then, changed weeks absent and got a phantom change of delivery option from 'on-farm' to group in the summary of changes at the bottom, even though the box still said 'on-farm pickup'. 

Then, I went into that section and changed it from 'on-farm' to a group drop-off. Then changed it back to 'on-farm' and noticed that the calendar boxes were duplicated below the original calendar.

This was for the '2017 Summer' signup.

**Comment by cbaron** [comment]
I was never able to reproduce the part where the delivery option is changed incorrectly in the summary, but I was able to fix the issue where the calendar boxes are duplicated.  I also found an issue when trying to change the delivery option when there is no group option selected.  I will make a change so that `None` for the group option can not be selected.  Perhaps that is how the summary become out of sync with everything.

If you can still reproduce the incorrect summary text after I push a fix, please try to provide another tidbit of info on how you did it.

Also, I wanted to confirm that if you change the delivery for someone, then we use the same weeks for dates absent.
